services:
    yii2-app:
        image: syedsalman041997/webapp:main
        ports:
            - "8000:80"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
