name: Deploy PHP to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      SERVICE_LOCATION: './'
      SERVICE_NAME: webapp
      EC2_CREATE: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date and branch name
        run: |
          echo "BUILD_TIME=$(date +'%Y-%m-%d-%H-%M-%S')"  >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

      - name: Set Image tag
        run: |
          echo "IMAGE=$NAMESPACE/$SERVICE_NAME:$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "IMAGE: $IMAGE & BRANCH_NAME : $BRANCH_NAME"
          echo "PWD : $PWD"
          cd ${{ env.SERVICE_LOCATION }}
          echo "PWD : $PWD"
          ls
          docker build . --build-arg SOURCE=mosip --build-arg COMMIT_HASH=$(git rev-parse HEAD) --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --build-arg BUILD_TIME=$BUILD_TIME --file Dockerfile --tag $IMAGE

      - name: Log into registry
        run: echo "${{secrets.RELEASE_DOCKER_HUB}}" | docker login -u ${{secrets.ACTOR_DOCKER_HUB}} --password-stdin

      - name: Push Image
        run: |
          docker push $IMAGE

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        if: "${{ env.EC2_CREATE == 'true' }}"
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE }}
            docker stack deploy -c ~/docker-compose/docker-compose.yaml webapp
